language: ruby
before_install:
  - gem install bundler
rvm:
  - 2.4.2
  - 2.3.1
env:
  - RAILS_VERSION=5.2
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.0
matrix:
  exclude:
    - env: RAILS_VERSION=5.0
      rvm: 2.1.10
fast_finish: true
