language: ruby
before_install:
  - gem install bundler
rvm:
  - 2.3.2
  - 2.2.6
  - 2.1.10
env:
  - RAILS_VERSION=5.0
  - RAILS_VERSION=4.2
matrix:
  exclude:
    - env: RAILS_VERSION=5.0
      rvm: 2.1.10
fast_finish: true
